const jokers = [
  {
    name: "Chill Joker",
    text: [
      "{X:mult,C:white}X2{} Mult divided",
      "by game speed",
      "{C:inactive}(Currently {X:mult,C:white}X2{C:inactive} Mult)",
    ],
    badge: "Rare",
    image: "j_aiz_chill_joker",
  },
  {
    name: "Loudspeaker",
    text: [
      "Gives {C:chips}Chips{} based",
      "on {C:attention}Audio volume{}",
      "{C:inactive}(Currently {C:chips}+100{C:inactive} Chips)",
    ],
    badge: "common",
    image: "j_aiz_loudspeaker",
  },
  {
    name: "Easy Mode",
    text: [
      "Gives {C:mult}+1 mult{} for",
      "every 2 jokers with",
      "{C:attention}White stickers{}",
      "in your collection",
      "{C:inactive}(Currently {C:mult}+0{C:inactive} Mult)",
    ],
    badge: "uncommon",
    image: "j_aiz_easy_mode",
  },
  {
    name: "Blåhaj",
    text: ["{C:dark_edition}+1{} Joker slots"],
    badge: "common",
    image: "j_aiz_blåhaj",
    soul: true,
  },
  {
    name: "AntiBubzia",
    text: [
      "Plays the exact",
      "same hand backwards",
      "to cancel out",
      "your score",
      "every {C:attention}freaking{} time",
    ],
    badge: "rare",
    image: "j_aiz_antibubzia",
  },
  {
    name: "Too Much To Handle",
    text: [
      "At end of round",
      "set a random hand size",
      "between {C:attention}4{} and {C:attention}15",
      "{C:inactive}(Currently {C:attention}-1{C:inactive} hand size)",
    ],
    badge: "rare",
    image: "j_aiz_hands",
  },
  {
    name: "poker hand xmult WIP",
    text: [
      "This Joker Gains {X:mult,C:white}X0.5{} Mult",
      "per {C:attention}consecutive unique{}",
      "hand played, reset on",
      "{C:attention}non unique{} hand played",
      "{C:inactive}(Currently {X:mult,C:white}X1{C:inactive} Mult)",
    ],
    badge: "Rare",
    image: "j_aiz_poker_hand_xmult",
  },
  {
    name: "Penny",
    text: [
      "At end of round,",
      "duplicate {C:attention}All{} cards",
      "in your deck",
    ],
    badge: "rare",
    image: "j_aiz_penny",
  },
  {
    name: "Trollker",
    text: [
      "This Joker gains {X:mult,C:white}X0.5",
      "Mult at end of round.",
      "This joker may do",
      "a little bit of {C:attention,E:1,S:1.1}Trolling",
      "{C:inactive}(Currently {X:mult,C:white}X2{C:inactive})",
    ],
    badge: "Rare",
    image: "j_aiz_trollker",
  },
  {
    name: "Pawn",
    text: [
      "Advances at end of round",
      "Adds current rank to mult",
      "{C:inactive}(Currently on rank {C:attention}2{C:inactive})",
    ],
    badge: "common",
    image: "j_aiz_pawn",
  },
  {
    name: "Knight",
    text: [
      "Converts scored {C:attention}Dark{} suits",
      "To random {C:attention}Light{} suits",
      "Converted cards give {C:mult}+10{} Mult",
      "{s:0.8}Flips conversion at end of round{}",
    ],
    badge: "uncommon",
    image: "j_aiz_knight",
  },
  {
    name: "Bishop",
    text: [
      "Scored Numbered cards",
      "earn {C:money}$1{}",
      "Scored Face cards",
      "{C:attention}lose{} {C:money}$1",
    ],
    badge: "uncommon",
    image: "j_aiz_bishop",
  },
  {
    name: "Rook",
    text: [
      "Discarded cards are",
      "turned to stone",
      "{C:attention}-1{} discards",
    ],
    badge: "rare",
    image: "j_aiz_rook",
  },
  {
    name: "Queen",
    text: [
      "When round begins,",
      "destroy all cards",
      "of {C:attention}lowest{} rank",
      "in your full deck.",
      "This Joker gains {X:mult,C:white}X{} Mult",
      "for each card destroyed",
      "{C:inactive}Currently {X:mult,C:white}X1{} Mult",
    ],
    badge: "rare",
    image: "j_aiz_queen",
  },
  {
    name: "King",
    text: ["Other {C:attention}Chess Jokers", "Give {X:mult,C:white}X5{} Mult"],
    badge: "legendary",
    image: "j_aiz_king",
    soul: true,
  },
  {
    name: "Jay-Z",
    text: [
      "{C:green}1 in 10{} chance this",
      "card is destroyed and",
      "{C:dark_edition}Polychrome{} is added",
      "to {C:attention}All{} cards",
      "at end of round",
    ],
    badge: "legendary",
    image: "j_aiz_jay_z",
    soul: true,
  },
];
export { jokers };
